ingress:
  annotations:
    konghq.com/https-redirect-status-code: "301"
    konghq.com/protocols: https
    konghq.com/strip-path: "false"
  className: kong
  enabled: true
  hosts:
  - host: docs.eidp.com
    paths:
    - path: /
      pathType: Prefix
  tls:
  - hosts:
    - docs.eidp.com
