apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: platform-documentation-repo
  labels:
    app.kubernetes.io/name: platform-documentation
spec:
  interval: 1m
  provider: generic
  secretRef:
    name: eidp-harbor-pull-credential
  type: oci
  url: oci://cr.eidp.io/platform-documentation/charts
