name: common

on:
  pull_request:
    branches:
      - main

jobs:
  common:
    uses: eidp/actions-common/.github/workflows/common.yml@8c3a21b463a1323f4b91307c0505ef837bbc8090 # v1.3.5
    with:
      runs-on: kubernetes-runner
    permissions:
      pull-requests: write
      issues: write
