name: release

on:
  push:
    tags:
    - '*.*.*'

jobs:
  release:
    runs-on: kubernetes-runner

    permissions:
      contents: read
      actions: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Fetch commit version
      id: fetch-commit-version
      uses: eidp/actions-semver/fetch-commit-version@d4f33761d7dafbeff3241fe8afe927a1d7516703 # v0.4.0
      with:
        workflow-name: build

    - name: Get commit SHA
      id: commit-sha
      uses: eidp/actions-common/commit-sha@8c3a21b463a1323f4b91307c0505ef837bbc8090 # v1.3.5

    - name: Promote Docker Image
      id: promote-image
      uses: eidp/actions-docker/promote@326947db030d535fe2ca7a59801fcf2621de5aea # v0.1.2
      with:
        image: ${{ vars.HARBOR_HOST }}/platform-documentation
        registry: ${{ vars.HARBOR_HOST }}
        registry-username: ${{ secrets.HARBOR_USERNAME }}
        registry-password: ${{ secrets.HARBOR_PASSWORD }}
        source-tag: ${{ steps.commit-sha.outputs.short-sha }}
        target-tag: '${{ github.ref_name }}'

    - name: Helm Promote
      uses: eidp/actions-helm/promote@5fbdd1fff2866d3104da9986b98e0b88e6c7aa4e # v1.0.0
      with:
        chart: oci://${{ vars.HARBOR_HOST }}/charts/platform-documentation
        source-version: ${{ steps.fetch-commit-version.outputs.version }}
        target-version: '${{ github.ref_name }}'
        patch-docker-image: 'true'
        target-docker-image-version: '${{ github.ref_name }}'
        repo-url: oci://${{ vars.HARBOR_HOST }}/charts
        repo-user: ${{ secrets.HARBOR_USERNAME }}
        repo-password: ${{ secrets.HARBOR_PASSWORD }}
