name: renovate
on:
  schedule:
  - cron: '16/30 * * * *'
jobs:
  renovate:
    runs-on: dind-runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Run Renovate
      uses: eidp/actions-common/renovate@8c3a21b463a1323f4b91307c0505ef837bbc8090 # v1.3.5
      with:
        github-app-id: ${{ secrets.DEP_MANAGER_GITHUB_APP_ID }}
        github-app-pem: ${{ secrets.DEP_MANAGER_GITHUB_APP_PEM_FILE }}
        all-secrets: ${{ toJSON(secrets) }}
