name: testing-environment

on:
  push:
    branches:
    - main

jobs:
 verify-test-deployment:
    runs-on: kubernetes-runner

    permissions:
      actions: read
      contents: read
      id-token: write
      deployments: write

    environment: testing
    concurrency:
      group: testing-environment
      cancel-in-progress: true

    steps:
    # This step fetches the semantic version based on the commit history.
    # The same version should be used to tag the Helm chart, in case your repository contains one.
    - name: Checkout code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Fetch commit version
      id: commit-version
      uses: eidp/actions-semver/fetch-commit-version@23e971a676eb1fd1ec19999d367ec3fb3c4c31d4 # v0.4.1
      with:
        workflow-name: build  # The name of the workflow that builds the artifacts Docker container / Helm chart

    - name: Create Kubernetes context
      id: create-context
      uses: eidp/actions-kubernetes/create-context@8432c0e87a8145d73b12f299cefaf02479827ba7 # v2.1.1
      with:
        cluster: testing
        api-server: ${{ vars.K8S_API_SERVER_TESTING }}
        certificate-authority-data:
          ${{ secrets.K8S_CERTIFICATE_AUTHORITY_DATA_TESTING }}
        keycloak-url: ${{ vars.KEYCLOAK_URL }}
        token-exchange-client-id: ${{ secrets.TOKEN_EXCHANGE_CLIENT_ID }}
        token-exchange-client-secret: ${{ secrets.TOKEN_EXCHANGE_CLIENT_SECRET }}

    - name: Verify deployment test environment
      uses: eidp/actions-kubernetes/verify-up@8432c0e87a8145d73b12f299cefaf02479827ba7  # v2.1.1
      with:
        environment: testing
        kubernetes-context: testing
        namespace: apps-platform-documentation
        flux-resource: helmrelease/platform-documentation
        chart-version: '${{ steps.commit-version.outputs.version }}'
        github-token: ${{ github.token }}
